.TH "lib/menuoption.h" 3 "Sun Dec 4 2022" "greenland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/menuoption.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBMenuOption\fP \fBMenuOption\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMenuOption\fP { \fBPLANT_TREE\fP = 1, \fBQUERY_TREE\fP, \fBUPDATE_TREE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmoption_handle\fP (\fBMenuOption\fP mo)"
.br
.ti -1c
.RI "void \fBmoption_display\fP (\fBMenuOption\fP *opt)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
2022-11-16 23:05:32 PM +0800 
.RE
.PP

.PP
Definition in file \fBmenuoption\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBMenuOption\fP \fBMenuOption\fP"
MenuOption defines available options in the client menu 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMenuOption\fP"
MenuOption defines available options in the client menu 
.PP
Definition at line \fB11\fP of file \fBmenuoption\&.h\fP\&.
.PP
.nf
11 { PLANT_TREE = 1, QUERY_TREE, UPDATE_TREE } MenuOption;
.fi
.SH "Function Documentation"
.PP 
.SS "void moption_display (\fBMenuOption\fP * opt)"
Display menu options
.PP
\fBParameters\fP
.RS 4
\fIopt\fP A MenuOption got from user's input 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBmenuoption\&.c\fP\&.
.PP
.nf
23 {
24   printf("  ________                               \&.__                       \&.___ \n");
25   printf(" /  _____/_______   ____   ____    ____  |  |  _____     ____    __| _/ \n");
26   printf("/   \\  ___\\_  __ \\_/ __ \\_/ __ \\  /    \\ |  |  \\__  \\   /    \\  / __ |  \n");
27   printf("\\    \\_\\  \\|  | \\/\\  ___/\\  ___/ |   |  \\|  |__ / __ \\_|   |  \\/ /_/ |  \n");
28   printf(" \\______  /|__|    \\___  >\\___  >|___|  /|____/(____  /|___|  /\\____ |  \n");
29   printf("        \\/             \\/     \\/      \\/            \\/      \\/      \\/  \n\n");
30 
31   printf("Welcome to greenland, a place to plant tree!\n\n");
32   printf("We don't have any affiliation to the Greenland government, but if \n"
33          "you can plant a tree there, we are more than welcome! :)\n");
34 
35   printf("################################\n");
36   printf("#                              #\n");
37   printf("#            MENU              #\n");
38   printf("#                              #\n");
39   printf("################################\n\n");
40   printf("\t1\&. To plant a tree\n");
41   printf("\t2\&. To query a tree\n");
42   printf("\t3\&. To update a tree's status\n");
43   printf("(Choose a service needed according to the number)\n\n");
44   printf("Option: ");
45   scanf("%d", (int*) opt);
46   system("clear");
47 }
.fi
.SS "char * moption_handle (\fBMenuOption\fP mo)"
Handles menu option
.PP
\fBParameters\fP
.RS 4
\fImo\fP A MenuOption enum to be handle
.RE
.PP
\fBReturns\fP
.RS 4
0 if the handling succeeded, -1 if failed 
.RE
.PP

.PP
Definition at line \fB5\fP of file \fBmenuoption\&.c\fP\&.
.PP
.nf
6 {
7   char* msg = malloc(1024);
8 
9   switch (mo) {
10     case PLANT_TREE:
11     case QUERY_TREE:
12     case UPDATE_TREE:
13       sprintf(msg, "Option %d soon to be supported\n", mo);
14       return msg;
15 
16     default:
17       sprintf(msg, "Option %d not supported\n", mo);
18       return msg;
19   }
20 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for greenland from the source code\&.
