.TH "lib/tree_coordinate.h" 3 "Fri Jan 6 2023" "greenland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/tree_coordinate.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtree_coordinate\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtree_coordinate\fP \fBtree_coordinate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtree_set_x\fP (\fBtree_coordinate\fP *c, int x)"
.br
.ti -1c
.RI "void \fBtree_set_y\fP (\fBtree_coordinate\fP *c, int y)"
.br
.ti -1c
.RI "int \fBtree_get_x\fP (const \fBtree_coordinate\fP *c)"
.br
.ti -1c
.RI "int \fBtree_get_y\fP (const \fBtree_coordinate\fP *c)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
2022-11-14 10:32:23 AM +0800 
.RE
.PP

.PP
Definition in file \fBtree_coordinate\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for greenland from the source code\&.
