.TH "tree_coordinate" 3 "Fri Jan 6 2023" "greenland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree_coordinate
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file tree_coordinate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for greenland from the source code\&.
