.TH "Tree" 3 "Fri Jan 6 2023" "greenland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tree
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBstr_size\fP"
.br
.ti -1c
.RI "char * \fBspecies\fP"
.br
.ti -1c
.RI "\fBtree_state\fP \fBstatus\fP"
.br
.ti -1c
.RI "struct tm * \fBday_planted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTree\fP data class that stores information about a tree including its species, its status, and the amount of days it has lived\&. 
.PP
Definition at line \fB17\fP of file \fBtree\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "struct tm* Tree::day_planted"
The day when the tree was planted 
.PP
Definition at line \fB25\fP of file \fBtree\&.h\fP\&.
.PP
Referenced by \fBtree_create()\fP, \fBtree_free()\fP, \fBtree_get_day_planted()\fP, \fBtree_serialise()\fP, and \fBtree_set_day_planted()\fP\&.
.SS "char* Tree::species"
Species name of the tree 
.PP
Definition at line \fB21\fP of file \fBtree\&.h\fP\&.
.PP
Referenced by \fBtree_free()\fP, \fBtree_get_species()\fP, \fBtree_serialise()\fP, and \fBtree_set_species()\fP\&.
.SS "\fBtree_state\fP Tree::status"
Status of the tree 
.PP
Definition at line \fB23\fP of file \fBtree\&.h\fP\&.
.PP
Referenced by \fBtree_get_status()\fP, \fBtree_serialise()\fP, and \fBtree_set_status()\fP\&.
.SS "unsigned long Tree::str_size"
String size of species string 
.PP
Definition at line \fB19\fP of file \fBtree\&.h\fP\&.
.PP
Referenced by \fBtree_set_species()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for greenland from the source code\&.
