.TH "Tree" 3 "Fri Jan 6 2023" "greenland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tree
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBstr_size\fP"
.br
.ti -1c
.RI "char * \fBspecies\fP"
.br
.ti -1c
.RI "\fBtree_state\fP \fBstatus\fP"
.br
.ti -1c
.RI "struct tm * \fBday_planted\fP"
.br
.ti -1c
.RI "\fBtree_coordinate\fP \fBcoordinate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTree\fP data class that stores information about a tree including its species, its status, and the amount of days it has lived\&. 
.PP
Definition at line 30 of file tree\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtree_coordinate\fP Tree::coordinate"
The coordinate where the tree was planted 
.PP
Definition at line 40 of file tree\&.h\&.
.PP
Referenced by tree_get_coordinate(), and tree_set_coordinate()\&.
.SS "struct tm* Tree::day_planted"
The day when the tree was planted 
.PP
Definition at line 38 of file tree\&.h\&.
.PP
Referenced by tree_create(), tree_free(), and tree_get_day_planted()\&.
.SS "char* Tree::species"
Species name of the tree 
.PP
Definition at line 34 of file tree\&.h\&.
.PP
Referenced by tree_free(), tree_get_species(), and tree_set_species()\&.
.SS "\fBtree_state\fP Tree::status"
Status of the tree 
.PP
Definition at line 36 of file tree\&.h\&.
.PP
Referenced by tree_get_status(), and tree_set_status()\&.
.SS "unsigned long Tree::str_size"
String size of species string 
.PP
Definition at line 32 of file tree\&.h\&.
.PP
Referenced by tree_set_species()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for greenland from the source code\&.
