lib/tree.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <time.h>
#include `tree_state.h`
#include `tree_coordinate.h`
Data Structures
struct Tree
Typedefs
typedef struct Tree Tree
Functions
struct Tree * tree_create (const char *sp, tree_state st, const char *d, tree_coordinate c)
void tree_free (Tree *t)
char * tree_get_species (const Tree *t)
tree_state tree_get_status (const Tree *t)
struct tm * tree_get_day_planted (const Tree *t)
tree_coordinate tree_get_coordinate (const Tree *t)
void tree_set_species (Tree *t, const char *sp)
void tree_set_status (Tree *t, tree_state st)
void tree_set_day_planted (Tree *t, const char *d)
void tree_set_coordinate (Tree *t, tree_coordinate c)
Detailed Description
Date
2022-11-11 23:27:54 PM +0800
Typedef Documentation
Tree
typedef struct Tree Tree
Tree data class that stores information about a tree including its species, its status, and the amount of days it has lived.
Function Documentation
tree_create()
struct Tree* tree_create (const char * sp, tree_state st, const char * d, tree_coordinate c)
Create a Tree data class
Parameters
 in sp A string specifies the species name for the Tree
 in st A Tree State enum specifies the current status for the Tree
 in d A string specifies the days alived of the Tree in format Y-m-d, e.g. 2022-12-05
 in c A Tree coordinate struct that specify the longitude and latitude coordinate of the planted tree
Returns
A Tree data class that contains the information about its species name, current status and the amount of days alived.
Attention
st must be valid
Definition at line 11 of file tree.c.
{
  Tree *new_tree = malloc(sizeof(Tree));
  tree_set_species(new_tree, sp);
  tree_set_status(new_tree, st);
  new_tree->day_planted = NULL;
  tree_set_day_planted(new_tree, d);
  tree_set_coordinate(new_tree, c);
  return new_tree;
}
References Tree::day_planted, tree_set_coordinate(), tree_set_day_planted(), tree_set_species(), and tree_set_status().
tree_free()
void tree_free (Tree * t)
Destroy a Tree data class
Parameters
 in t A tree data class to be destroyed
Definition at line 59 of file tree.c.
{
  free(t->day_planted);
  free(t->species);
  free(t);
}
References Tree::day_planted, and Tree::species.
tree_get_coordinate()
tree_coordinate tree_get_coordinate (const Tree * t)
Get Tree's the current coordinate
Parameters
 in t A pointer to a Tree
Returns
A pointer to struct tree_coordinate indicates the coordinate where the Tree was planted
Definition at line 81 of file tree.c.
{
  return t->coordinate;
}
References Tree::coordinate.
tree_get_day_planted()
struct tm* tree_get_day_planted (const Tree * t)
Get Tree's the amount of days it has lived
Parameters
 in t A pointer to a Tree
Returns
A pointer to struct tm indicates the day when the Tree was planted
Definition at line 76 of file tree.c.
{
  return t->day_planted;
}
References Tree::day_planted.
tree_get_species()
char* tree_get_species (const Tree * t)
Get Tree's species name
Parameters
 in t A pointer to a Tree
Returns
A string that describes the Tree's species name
Definition at line 66 of file tree.c.
{
  return t->species;
}
References Tree::species.
tree_get_status()
tree_state tree_get_status (const Tree * t)
Get Tree's current status
Parameters
 in t A pointer to a Tree
Returns
A non-negative integer indicates the Tree's current status
Definition at line 71 of file tree.c.
{
  return t->status;
}
References Tree::status.
Referenced by tree_set_day_planted().
tree_set_coordinate()
void tree_set_coordinate (Tree * t, tree_coordinate c)
Set Tree's coordinate where it was planted
Parameters
 out t A modified Tree with changed planted coordinate
 in d A struct specifies the coordinate
Definition at line 125 of file tree.c.
{
  t->coordinate = c;
}
References Tree::coordinate.
Referenced by tree_create().
tree_set_day_planted()
void tree_set_day_planted (Tree * t, const char * d)
Set Tree's when it was planted
Parameters
 out t A modified Tree with changed planted day
 in d A string specifies the planted day
Definition at line 105 of file tree.c.
{
  if (tree_get_status(t) == DEAD)
  {
    printf("debug: it is dead\n");
    t->day_planted = NULL;
  }
  else
  {
    printf("debug: it is alive\n");
    if (!t->day_planted)
    { // handle the case when day_planted haven't allocated with memory
      printf("debug: day_planted is null\n");
      t->day_planted = malloc(sizeof(struct tm));
    }
    printf("debug: date: %s\n", d);
    strptime(d, "%F", t->day_planted);
  }
}
References tree_get_status().
Referenced by tree_create().
tree_set_species()
void tree_set_species (Tree * t, const char * sp)
Set Tree's species name
Parameters
 out t A modified Tree with changed species name
 in sp A string indicates a species name
Definition at line 86 of file tree.c.
{
  if ((t->str_size = strlen(sp) + 1) > 0)
  {
    t->species = calloc(t->str_size, sizeof(char));
    strncpy(t->species, sp, t->str_size);
  }
  else
  {
    t->str_size = 0;
    t->species = NULL;
  }
}
References Tree::species, and Tree::str_size.
Referenced by tree_create().
tree_set_status()
void tree_set_status (Tree * t, tree_state st)
Set Tree's current status
Parameters
 out t A modified Tree with changed status
 in st A Tree State enum
Definition at line 100 of file tree.c.
{
  t->status = st;
}
References Tree::status.
Referenced by tree_create().